apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: etcd
    image: quay.io/coreos/etcd:v3.5.10
    command:
    - etcd
    - --advertise-client-urls=http://10.0.0.232:2379
    - --listen-client-urls=http://0.0.0.0:2379
    - --data-dir=/var/lib/etcd
    - --listen-peer-urls=http://0.0.0.0:2380
    - --initial-cluster=default=http://10.0.0.232:2380
    - --initial-advertise-peer-urls=http://10.0.0.232:2380
    - --initial-cluster-state=new
    - --initial-cluster-token=test-token
    volumeMounts:
    - name: etcd-data
      mountPath: /var/lib/etcd
  volumes:
  - name: etcd-data
    hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
